#include "overloaded.hpp"
#include <functional>
#include <git2.h>
#include <git2/oid.h>
#include <git2/types.h>
#include <ios>
#include <iostream>
#include <memory>
#include <newtype.hpp>
#include <tuple>
#include <type_traits>
#include <union.hpp>
#include <utility>
